$(document).ready(function(){
  $("a.about").click(function(){
      $("#about").show();
      $("#photography").hide();
      $("#portfolio").hide();
      $("#contact").hide();
  });
  $("a.photography").click(function(){
      $("#photography").show();
      $("#about").hide();
      $("#portfolio").hide();
      $("#contact").hide();
  });
  $("a.portfolio").click(function(){
      $("#portfolio").show();
      $("#about").hide();
      $("#photography").hide();
      $("#contact").hide();
  });
  $("a.contact").click(function(){
      $("#contact").show();
      $("#about").hide();
      $("#photography").hide();
      $("#portfolio").hide();
  });
});